# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96d5a1003e8516058438f39d509f87a14dfd6bb228a947d86d25a125730d186b22d42db6520c71d9b94aa17154211dbfdf7ca88b44e7752595511fd45040ef8c

test:
  secret_key_base: 5542dacded258ed7c0e4959a160f8c9af058e6d9871caac75cf78229fd8b584c8caec158417a538b0a02597fa7ea21807724d77c18f88b154bce8657d5675eae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
